<?php

return [
	'category' => [
		1 => 'Công nghệ',
		2 => 'Đời sống',
		3 => 'Khám phá khoa học',
		4 => 'Khoa học vũ trụ',
		5 => '1001 bí ẩn',
		6 => 'Y học - Sức khỏe',
		7 => 'Công nghệ mới',
		8 => 'Phần mềm hữu ích',
		9 => 'Khoa học máy tính',
		10 => 'Phát minh khoa học',
		11 => 'AI - Trí tuệ nhân tạo',
		12 => 'Sinh vật học',
		13 => 'Khảo cổ học',
		14 => 'Đại dương học',
		15 => 'Thế giới động vật',
		16 => 'Danh nhân thế giới',
		17 => 'Ngày tận thế',
		18 => 'Chinh phục ngôi sao',
		19 => 'Kỳ quan thế giới',
		20 => 'Người ngoài hành tinh',
		21 => 'Trắc nghiệm khoa học',
		22 => 'Lịch sử',
		23 => 'Khoa học quân sự',
		24 => 'Bệnh và thông tin bệnh',
		25 => 'Môi trường',
		26 => 'Bệnh ung thư',
		27 => 'Ứng dụng khoa học',
		28 => 'Khoa học và bạn đọc',
		29 => 'Công trình khoa học',
		30 => 'Câu chuyện khoa học',
		31 => 'Sự kiện khoa học',
		32 => 'Thư viện ảnh',
		33 => 'Góc hài hước',
		34 => 'Video',
	]
];
